/* Phase 2 operational-core additions. Generated by build_phase2_data.py. */
window.NERC = window.NERC || {};
(function(){
  var modules = {}; (window.NERC.content || []).forEach(function(m){ modules[m.id]=m; });
  if (modules["foundations"]) modules["foundations"].sections.push.apply(modules["foundations"].sections, [
  {
    "id": "f-human-performance",
    "title": "Human performance in the control room",
    "body": [
      {
        "t": "p",
        "html": "Reliable operation depends on technical knowledge and on disciplined habits that make errors less likely. {{human-performance|Human performance}} tools are not signs that an operator lacks skill. They are defenses against distraction, fatigue, time pressure, and assumptions."
      },
      {
        "t": "h",
        "text": "Five habits to practice from day one"
      },
      {
        "t": "list",
        "items": [
          "<strong>{{self-check|Self-check}}</strong>: stop, touch or point to the intended control, state the expected result, act, and verify the actual result.",
          "<strong>{{peer-check|Peer check}}</strong>: have another qualified person independently confirm a high-risk step before it is performed.",
          "<strong>{{placekeeping|Placekeeping}}</strong>: mark each procedure step as it is completed so no step is skipped or repeated.",
          "<strong>Three-part communication</strong>: issue the instruction, repeat it back, then confirm or correct it before action.",
          "<strong>{{stop-work|Stop-work behavior}}</strong>: pause when conditions do not match the procedure, one-line, or expected response."
        ]
      },
      {
        "t": "note",
        "kind": "op",
        "title": "Use the tool that matches the risk",
        "html": "A peer check does not replace the operator's own verification. A procedure does not replace situational awareness. When the plant response differs from the expected response, stop and resolve the mismatch before continuing."
      },
      {
        "t": "scenario",
        "title": "The breaker that did not move",
        "role": "Transmission Operator",
        "setup": "You issue a remote open command to breaker 52-4. The control indication changes to OPEN, but line MW and current remain nearly unchanged.",
        "steps": [
          {
            "stem": "What is the best immediate response?",
            "options": [
              "Continue to the next switching step because the status changed",
              "Repeat the open command several times",
              "Stop the switching sequence, verify the equipment state using independent indications, and communicate the discrepancy",
              "Assume the MW value is delayed and mark the step complete"
            ],
            "answer": 2,
            "explain": "The expected electrical response did not occur. Use stop-work behavior, preserve placekeeping, and verify with independent data or local confirmation before continuing.",
            "optFeedback": {
              "0": "A changed status point is not enough when analog values contradict it.",
              "1": "Repeated commands can create additional risk without resolving the actual state.",
              "3": "Treating the mismatch as delay is an unsupported assumption."
            }
          }
        ],
        "debrief": "The safest operator is not the one who never pauses. It is the one who recognizes when the system no longer matches the mental model and deliberately rebuilds that model before acting."
      }
    ]
  }
]);
  if (modules["transmission-ops"]) modules["transmission-ops"].sections.push.apply(modules["transmission-ops"].sections, [
  {
    "id": "m1-ems-data-quality",
    "title": "SCADA, EMS, and data quality",
    "body": [
      {
        "t": "p",
        "html": "The control room display is the end of a long information chain. Field instruments feed an {{ied|IED}} or {{rtu|RTU}}. Communications move the data to front-end systems and the {{scada|SCADA}} database. The {{ems|EMS}} uses that data, the network model, and breaker topology to run the {{state-estimator|state estimator}}, power flow, and contingency analysis."
      },
      {
        "t": "h",
        "text": "What each layer contributes"
      },
      {
        "t": "list",
        "items": [
          "<strong>Field measurements</strong>: breaker status, MW, MVAR, voltage, current, frequency, and alarms.",
          "<strong>Communications and data exchange</strong>: utility channels, protocols, and {{iccp|ICCP}} links between control centers.",
          "<strong>{{topology-processor|Topology processing}}</strong>: converts breaker and switch positions into the buses, branches, and islands used by analysis tools.",
          "<strong>State estimation</strong>: combines measurements with the model to create a consistent estimate of system conditions and identify likely bad data.",
          "<strong>Contingency analysis</strong>: tests credible outages against the estimated state."
        ]
      },
      {
        "t": "p",
        "html": "Operators should distinguish data that are <strong>good</strong>, <strong>questionable</strong>, <strong>{{stale-telemetry|stale}}</strong>, manually substituted, failed, or inconsistent. A value can look numerically reasonable and still be wrong because its timestamp is old, its device mapping is wrong, or the topology model does not match the actual yard."
      },
      {
        "t": "note",
        "kind": "op",
        "title": "Trust, but verify",
        "html": "A converged state estimator is useful evidence, not proof that every value is correct. A failed state estimator is a warning that the network model, topology, or measurements may not support a dependable assessment. Use neighboring indications, trends, redundant meters, local confirmation, and reasonableness checks."
      },
      {
        "t": "interactive",
        "id": "badDataLab"
      },
      {
        "t": "scenario",
        "title": "The open breaker with live current",
        "role": "Transmission Operator",
        "setup": "A planned bus split was just completed. SCADA shows the line breaker OPEN, but the line still shows 168 MW and 412 A. The state estimator has stopped converging.",
        "steps": [
          {
            "stem": "Which diagnosis should lead your response?",
            "options": [
              "The line is definitely open; analog values can be ignored",
              "The status, analog data, and model disagree, so the actual topology is uncertain",
              "The state estimator failed only because the system is lightly loaded",
              "The line must have become an island"
            ],
            "answer": 1,
            "explain": "The evidence is internally inconsistent. Treat topology as uncertain, stop dependent switching, and verify the physical state and data mapping.",
            "optFeedback": {
              "0": "A status point alone cannot overrule contradictory current and MW.",
              "2": "Load level does not explain away the direct mismatch.",
              "3": "An island cannot be concluded from these indications."
            }
          },
          {
            "stem": "What is the best next action?",
            "options": [
              "Continue the order and fix the model later",
              "Delete the bad analog values so the state estimator will converge",
              "Hold further switching, notify affected operators, obtain independent or local verification, and correct the model or telemetry",
              "Open adjacent breakers to force the display to match"
            ],
            "answer": 2,
            "explain": "Protect the system from acting on an unknown configuration. Coordinate, verify, then restore a trustworthy model before resuming.",
            "optFeedback": {
              "0": "Continuing compounds risk while the topology is uncertain.",
              "1": "Removing data to force convergence can hide the real problem.",
              "3": "Additional switching without a verified state can worsen the event."
            }
          }
        ],
        "debrief": "A display is an instrument, not the system itself. Operator judgment comes from reconciling status, analog values, time stamps, alarms, model results, and communications."
      }
    ]
  }
]);
  if (modules["voltage-reactive"]) modules["voltage-reactive"].sections.push.apply(modules["voltage-reactive"].sections, [
  {
    "id": "m2-control-devices",
    "title": "Voltage-control equipment and generator limits",
    "body": [
      {
        "t": "p",
        "html": "Voltage control is a local and regional coordination problem. Reactive support is generally most effective near the need because reactive flow increases current, losses, and voltage drop. Operators therefore choose among devices based on location, speed, available range, and the condition that created the problem."
      },
      {
        "t": "h",
        "text": "Common controls"
      },
      {
        "t": "list",
        "items": [
          "<strong>Generator excitation and {{avr|AVR}}</strong>: fast, continuously variable voltage support within the unit's {{generator-capability-curve|capability curve}}.",
          "<strong>Shunt capacitors and reactors</strong>: switched devices that add or absorb reactive power.",
          "<strong>{{svc|SVC}} and {{statcom|STATCOM}}</strong>: fast power-electronic reactive controls.",
          "<strong>{{ltc|Load tap changer}}</strong>: changes transformer ratio. It can improve distribution voltage while increasing load and reactive demand seen by a weak transmission source.",
          "<strong>Synchronous condenser</strong>: rotating equipment that supplies or absorbs MVAR and contributes short-circuit strength."
        ]
      },
      {
        "t": "p",
        "html": "A generator may approach a field-current or stator-current limit. The {{oel|overexcitation limiter}} protects against excessive field current; the {{uel|underexcitation limiter}} protects against unsafe underexcited operation. When the unit reaches a limit, its remaining {{reactive-reserve|reactive reserve}} shrinks and its ability to hold voltage during the next contingency can be reduced."
      },
      {
        "t": "interactive",
        "id": "voltageDispatch"
      },
      {
        "t": "scenario",
        "title": "A weak load pocket after a line outage",
        "role": "Transmission Operator",
        "setup": "A line outage drops the load-pocket transmission bus to 0.92 pu. The local generator is producing 225 MVAR with a 250 MVAR capability, and distribution LTCs are beginning to raise taps.",
        "steps": [
          {
            "stem": "Which action principle is most important?",
            "options": [
              "Raise all LTCs first because they directly raise customer voltage",
              "Use nearby reactive sources and coordinate generator support while preventing controls from exhausting the remaining margin",
              "Reduce local generation so the generator produces fewer MVAR",
              "Switch in a reactor to absorb reactive power"
            ],
            "answer": 1,
            "explain": "Support the weak transmission voltage near the need, preserve generator margin, and manage LTC behavior so it does not deepen the transmission-side problem.",
            "optFeedback": {
              "0": "LTC action can increase the burden on a weak source even while local voltage briefly improves.",
              "2": "Reducing local generation may increase transfers and voltage drop.",
              "3": "A reactor absorbs MVAR and would usually worsen a low-voltage condition."
            }
          }
        ],
        "debrief": "The best voltage action is not simply the device that moves the number fastest. It is the coordinated action that restores voltage while preserving enough reactive margin for the next credible event."
      }
    ]
  }
]);
  if (modules["operating-limits"]) modules["operating-limits"].sections.push.apply(modules["operating-limits"].sections, [
  {
    "id": "m3-ratings-to-action",
    "title": "From Facility Ratings to real-time action",
    "body": [
      {
        "t": "p",
        "html": "A {{facility-rating|Facility Rating}} is an equipment capability. A {{sol|System Operating Limit}} is a system limit established for a specified configuration and operating condition. SOLs can be based on thermal loading, voltage, or stability. An {{irol|IROL}} is an SOL whose exceedance could lead to instability, uncontrolled separation, or cascading."
      },
      {
        "t": "h",
        "text": "The operator's analysis chain"
      },
      {
        "t": "list",
        "items": [
          "<strong>Actual state</strong>: are any current flows, voltages, or stability measures outside limits now?",
          "<strong>Post-contingency state</strong>: which credible loss creates the most severe result?",
          "<strong>{{limiting-contingency|Limiting contingency}}</strong>: the outage that drives the binding result.",
          "<strong>Corrective action</strong>: what action is available, how much relief will it provide, and how quickly can it be completed?",
          "<strong>Verification</strong>: rerun or review the assessment and confirm that all monitored results are acceptable."
        ]
      },
      {
        "t": "p",
        "html": "{{normal-rating|Normal ratings}} generally describe continuous capability. {{emergency-rating|Emergency ratings}} may allow higher loading for a specified time and condition. The applicable rating and time must come from the approved rating information and operating plan, not from a generic assumption."
      },
      {
        "t": "note",
        "kind": "alert",
        "title": "IROL timing is specific",
        "html": "Use the established {{irol-tv|IROL Tv}} for the particular IROL. Do not substitute a generic number. The operator needs to know when the clock starts, what actions are preplanned, and how completion will be verified."
      },
      {
        "t": "interactive",
        "id": "solIrolLab"
      },
      {
        "t": "scenario",
        "title": "Two contingencies, one urgent clock",
        "role": "Transmission Operator",
        "setup": "The actual interface flow is within its limit. Contingency X produces an IROL exceedance; Contingency Y produces a smaller SOL exceedance. A planned line return will not be complete within the IROL Tv.",
        "steps": [
          {
            "stem": "How should the actions be prioritized?",
            "options": [
              "Wait for the planned line return because it gives the largest relief",
              "Address only the current actual flow because no equipment is overloaded now",
              "Implement actions that can remove the IROL exceedance within its established time, then verify the SOL result and remaining contingencies",
              "Treat the SOL and IROL as identical because both are limits"
            ],
            "answer": 2,
            "explain": "The IROL consequence and time requirement drive immediate action. The plan must rely on actions that can actually be completed within the established time and must be verified by updated analysis.",
            "optFeedback": {
              "0": "An action that completes after the required time cannot be the primary mitigation.",
              "1": "Post-contingency risk is the reason real-time assessments are run before the outage occurs.",
              "3": "IROLs are a subset of SOLs with more severe potential consequences."
            }
          }
        ],
        "debrief": "Good limit management connects a number to its source, contingency, consequence, clock, available controls, and verification method."
      }
    ]
  }
]);
  if (modules["protection"]) modules["protection"].sections.push.apply(modules["protection"].sections, [
  {
    "id": "m4-event-reconstruction",
    "title": "Protection schemes and event reconstruction",
    "body": [
      {
        "t": "p",
        "html": "Protection systems detect abnormal electrical conditions and isolate only the equipment needed to clear the fault. The system is divided into overlapping {{protection-zone|protection zones}} around lines, buses, transformers, generators, and breakers. {{primary-protection|Primary protection}} is designed to clear the fault first; {{backup-protection|backup protection}} acts if the primary scheme or breaker does not complete the job."
      },
      {
        "t": "h",
        "text": "Schemes at operator depth"
      },
      {
        "t": "list",
        "items": [
          "<strong>{{distance-relay|Distance}}</strong>: estimates apparent impedance to locate line faults in zones.",
          "<strong>{{differential-relay|Differential}}</strong>: compares current entering and leaving a protected zone; a meaningful difference indicates an internal fault.",
          "<strong>{{directional-relay|Directional}}</strong>: determines whether fault current is flowing into or away from the protected direction.",
          "<strong>{{pilot-protection|Pilot and transfer-trip schemes}}</strong>: exchange information between terminals for fast, selective clearing.",
          "<strong>{{breaker-failure|Breaker-failure protection}}</strong>: trips surrounding breakers when the commanded breaker does not interrupt current."
        ]
      },
      {
        "t": "p",
        "html": "{{ct|Current transformers}} and {{pt-ccvt|voltage transformers or CCVTs}} provide relay inputs. Relay outputs operate trip coils, {{lockout-relay|lockout relays}}, reclosing logic, or communications-assisted trips. The operator reconstructs the event with breaker status, {{relay-target|relay targets}}, current, alarms, and the {{sequence-of-events|sequence-of-events record}}."
      },
      {
        "t": "note",
        "kind": "op",
        "title": "Operator question: what is isolated now?",
        "html": "Do not stop at naming the relay. Determine which protection zone operated, whether the expected breakers opened, whether reclosing is enabled or blocked, whether backup protection operated, and what new contingency exposure remains."
      },
      {
        "t": "interactive",
        "id": "protectionSOE"
      },
      {
        "t": "scenario",
        "title": "Primary breaker failure",
        "role": "Transmission Operator",
        "setup": "A line fault occurs near Station A. The line relay targets Zone 1. The Station A line breaker receives a trip but remains closed until breaker-failure protection trips the adjacent bus breakers. Automatic reclosing is blocked.",
        "steps": [
          {
            "stem": "What does the wider breaker operation most strongly indicate?",
            "options": [
              "Normal automatic reclosing",
              "A breaker-failure scheme acted to clear the fault through surrounding breakers",
              "A bus differential scheme definitely misoperated",
              "The fault was on every connected line"
            ],
            "answer": 1,
            "explain": "The primary breaker did not interrupt current, so breaker-failure protection removed the fault by tripping adjacent breakers. The result is a larger outage than the original line trip would have produced.",
            "optFeedback": {
              "0": "Reclosing attempts to restore a line after clearing; it does not explain adjacent breaker trips.",
              "2": "The evidence supports intended breaker-failure backup operation, not a definite misoperation.",
              "3": "Adjacent breakers can trip as backup without faults on each connected line."
            }
          },
          {
            "stem": "What should the operator communicate next?",
            "options": [
              "Only that the line is out",
              "The apparent faulted zone, failed breaker, breakers opened by backup protection, reclose status, and the resulting system exposure",
              "That protection engineering should reset all relays immediately",
              "That the event is complete because current is zero"
            ],
            "answer": 1,
            "explain": "Operational communication must describe the resulting topology and reliability impact, not merely the initiating fault. Preserve targets and records for the later misoperation review.",
            "optFeedback": {
              "0": "The wider topology change is critical to system assessment.",
              "2": "Evidence should be preserved and equipment status understood before resets.",
              "3": "Fault current clearing ends the fault, not the operator's assessment and coordination work."
            }
          }
        ],
        "debrief": "Protection knowledge helps the operator translate a burst of alarms into a physical story: fault, intended clearing, backup action, final topology, and remaining risk."
      }
    ]
  }
]);
  if (modules["emergency-ops"]) modules["emergency-ops"].sections.push.apply(modules["emergency-ops"].sections, [
  {
    "id": "m5-operating-plan-tabletop",
    "title": "Operating Plans, EEA, and degraded tools",
    "body": [
      {
        "t": "p",
        "html": "Emergency operation begins before the emergency. An {{operational-planning-analysis|Operational Planning Analysis}} identifies expected conditions, contingencies, risks, and actions. An {{operating-plan|Operating Plan}} turns that analysis into responsibilities, triggers, communications, and executable steps."
      },
      {
        "t": "h",
        "text": "Escalation without skipping steps"
      },
      {
        "t": "list",
        "items": [
          "Validate forecasts, outages, fuel or energy limitations, transfer capability, and resource availability.",
          "Secure available generation, imports, reserves, storage, {{demand-response|demand response}}, and {{interruptible-load|interruptible load}} according to plans and agreements.",
          "Coordinate emergency declarations and {{eea|Energy Emergency Alert}} actions through the applicable reliability process.",
          "Prepare controlled manual load shed if supply still cannot meet demand. {{ufls|UFLS}} and {{uvls|UVLS}} are protection backstops, not substitutes for deliberate operating action.",
          "Update the plan as conditions, forecasts, tools, and communications change."
        ]
      },
      {
        "t": "p",
        "html": "Loss of an application does not automatically mean loss of the control center, but it changes the minimum information needed to operate safely. Loss of {{loss-of-ems|EMS functions}}, state estimation, contingency analysis, ICCP, voice channels, or the primary control room each requires a defined fallback and risk response."
      },
      {
        "t": "note",
        "kind": "emergency",
        "title": "Degraded tools shrink the safe operating envelope",
        "html": "When analysis or visibility is degraded, operators may need more conservative limits, increased manual verification, additional communications, and reduced switching or transfers until dependable capability is restored."
      },
      {
        "t": "interactive",
        "id": "emergencyTabletop"
      },
      {
        "t": "scenario",
        "title": "Cold weather, constrained imports, fading visibility",
        "role": "Balancing and Transmission Operator",
        "setup": "Tomorrow's peak forecast rises by 800 MW. Two gas units report fuel risk, an import path is constrained by an outage, and several telemetry points become stale.",
        "steps": [
          {
            "stem": "What is the best first response?",
            "options": [
              "Wait for real-time frequency decline",
              "Revalidate the forecast and dependable resources, update the operating plan, coordinate with the RC and affected entities, and secure lower-impact mitigation",
              "Shed firm load immediately",
              "Assume the stale points are still accurate because they changed recently"
            ],
            "answer": 1,
            "explain": "The value of the planning horizon is time. Validate inputs, update the plan, coordinate actions, and build an escalation path before the peak arrives.",
            "optFeedback": {
              "0": "Waiting discards the available preparation time.",
              "2": "Firm load shed is a severe action used when necessary after available mitigation is evaluated.",
              "3": "Stale data must be treated as degraded information, not silently accepted."
            }
          },
          {
            "stem": "During the peak, the state estimator and contingency analysis fail while the constrained interface approaches its limit. What principle should guide operation?",
            "options": [
              "Maintain the same transfer because the last assessment was acceptable",
              "Increase the transfer to replace lost generation",
              "Use fallback monitoring, notify affected entities, apply conservative operating margins, and reduce risk until analysis is restored",
              "Disable alarms to reduce workload"
            ],
            "answer": 2,
            "explain": "Loss of analysis capability increases uncertainty. Use the documented fallback, strengthen coordination, and operate more conservatively rather than relying on a stale assessment.",
            "optFeedback": {
              "0": "The system and contingencies can change after the last successful run.",
              "1": "Increasing transfer adds risk while visibility is degraded.",
              "3": "Alarm management prioritizes useful information; it does not hide the condition."
            }
          }
        ],
        "debrief": "Emergency performance is a controlled progression: validate, coordinate, mitigate, escalate, and verify. The plan must still work when the normal tools do not."
      }
    ]
  }
]);
  if (modules["restoration"]) modules["restoration"].sections.push.apply(modules["restoration"].sections, [
  {
    "id": "m6-restoration-constraints",
    "title": "Restoration plans and electrical constraints",
    "body": [
      {
        "t": "p",
        "html": "A restoration plan identifies the strategy, {{blackstart|blackstart resources}}, {{cranking-path|cranking paths}}, priority loads, communication methods, coordination points, and conditions for reconnecting islands. The plan is local and RC-coordinated; it is not a universal switching recipe."
      },
      {
        "t": "h",
        "text": "Why energizing an empty system is difficult"
      },
      {
        "t": "list",
        "items": [
          "Long unloaded lines produce charging MVAR and can create high voltage and Ferranti rise.",
          "Transformer energization can create {{transformer-inrush|inrush current}} and temporary voltage distortion.",
          "A small island has little inertia and limited regulation, so each load pickup can move frequency sharply.",
          "{{station-service|Station service}} and generator {{auxiliary-load|auxiliary load}} must be restored before many units can start or remain stable.",
          "Synchronization requires acceptable voltage, frequency, phase-angle difference, and {{slip-frequency|slip frequency}}, plus the required authority and {{synch-check|synch-check}} conditions."
        ]
      },
      {
        "t": "note",
        "kind": "op",
        "title": "Build, measure, stabilize, then expand",
        "html": "After each energization or load pickup, verify frequency, voltage, MVAR, line charging, unit limits, and communications before proceeding. Restoration speed comes from prepared paths and disciplined verification, not from skipping stabilization steps."
      },
      {
        "t": "scenario",
        "title": "The planned cranking path is unavailable",
        "role": "Transmission Operator",
        "setup": "The blackstart unit starts, but the planned 230 kV cranking path cannot be used because its reactor is unavailable and station voltage rises when the first long line is energized.",
        "steps": [
          {
            "stem": "What is the best response?",
            "options": [
              "Continue the original path because restoration plans cannot be changed",
              "Add more unloaded lines to absorb the voltage",
              "Use the plan's alternate path or coordinated contingency process, manage reactive devices and generation, and verify voltage after each step",
              "Pick up the largest available load immediately"
            ],
            "answer": 2,
            "explain": "A restoration plan needs alternate paths and decision points. The operator controls charging and voltage step by step while coordinating changes with the RC and affected entities.",
            "optFeedback": {
              "0": "Plans include contingencies and coordination; forcing an unavailable path is unsafe.",
              "1": "Additional unloaded line charging can raise voltage further.",
              "3": "Large load pickup can collapse frequency in a small island."
            }
          }
        ],
        "debrief": "Restoration is a sequence of small, verified stable states. Each successful step creates the conditions for the next one."
      }
    ]
  }
]);
  if (modules["comms-coord"]) modules["comms-coord"].sections.push.apply(modules["comms-coord"].sections, [
  {
    "id": "m7-directives-fallback",
    "title": "Directives, failed channels, and data verification",
    "body": [
      {
        "t": "p",
        "html": "An {{operating-instruction|Operating Instruction}} is communicated for operating the interconnected system. A {{reliability-directive|Reliability Directive}} is an instruction issued to address a reliability condition under the applicable authority. In either case, the operator must understand the action before performing it."
      },
      {
        "t": "h",
        "text": "Close the loop"
      },
      {
        "t": "list",
        "items": [
          "The issuer states the action using clear nomenclature and numbers.",
          "The receiver performs a {{repeat-back|repeat-back}} of the instruction.",
          "The issuer gives an {{acknowledgment|acknowledgment}} that the repeat-back is correct or corrects it.",
          "The receiver reports completion, inability to comply, or changed conditions as required."
        ]
      },
      {
        "t": "p",
        "html": "If an instruction is unsafe, unclear, conflicts with equipment capability, or cannot be completed, do not silently substitute another action. State the concern or inability, provide the relevant reason, and request clarification or an alternative. Emergency authority does not remove the need for accurate communication."
      },
      {
        "t": "p",
        "html": "Communication continuity includes voice and data. When a hotline, phone, radio, ICCP link, or telemetry channel fails, use the documented alternate path, identify what information is no longer available, and increase verification until the primary channel returns."
      },
      {
        "t": "interactive",
        "id": "commsSimulator"
      },
      {
        "t": "scenario",
        "title": "Similar station names under high workload",
        "role": "Transmission Operator",
        "setup": "The RC directs you to open breaker 342 at Fairmont. Your system also has a Fairview station with breaker 342, and the voice channel is noisy.",
        "steps": [
          {
            "stem": "What is the correct response before action?",
            "options": [
              "Choose the station that seems more likely",
              "Repeat back the complete instruction including station, voltage level, breaker, and action, then wait for confirmation",
              "Ask a neighboring operator what they heard and act",
              "Open both breakers so the directive is certainly satisfied"
            ],
            "answer": 1,
            "explain": "Use complete nomenclature and repeat-back. Ambiguity must be removed by the issuer before action.",
            "optFeedback": {
              "0": "Inference is not a communication protocol.",
              "2": "A third party cannot replace issuer confirmation.",
              "3": "Taking an unissued action can create a second emergency."
            }
          }
        ],
        "debrief": "The purpose of communication protocol is not formality. It is to make sure the system action performed is the system action intended."
      }
    ]
  }
]);
  if (modules["balancing"]) modules["balancing"].sections.push.apply(modules["balancing"].sections, [
  {
    "id": "m8-interchange-recovery",
    "title": "Interchange lifecycle and disturbance recovery",
    "body": [
      {
        "t": "p",
        "html": "Interchange is more than a number in ACE. A transaction progresses from a request and {{arranged-interchange|Arranged Interchange}} through reliability evaluation and approval to {{confirmed-interchange|Confirmed Interchange}}. The Balancing Authorities then implement the agreed schedule and ramp, creating {{implemented-interchange|Implemented Interchange}}."
      },
      {
        "t": "h",
        "text": "What the operator watches"
      },
      {
        "t": "list",
        "items": [
          "<strong>{{e-tag|e-Tag}}</strong>: the electronic record used to communicate the transaction path, parties, profile, approvals, and changes.",
          "<strong>Ramp</strong>: the scheduled transition between interchange levels. The ramp changes scheduled interchange over time and therefore changes ACE.",
          "<strong>Curtailment</strong>: a coordinated reduction when reliability or transmission conditions require it.",
          "<strong>{{dynamic-schedule|Dynamic Schedule}} and {{pseudo-tie|Pseudo-Tie}}</strong>: arrangements that make remote resource output respond or appear in a BA's control and accounting differently from a fixed hourly schedule.",
          "<strong>{{inadvertent-interchange|Inadvertent interchange}}</strong>: the difference accumulated when actual and scheduled interchange do not match over time."
        ]
      },
      {
        "t": "p",
        "html": "During a {{rbce|Reportable Balancing Contingency Event}}, BAL-002 focuses on returning reporting ACE to the required recovery value within the applicable {{contingency-event-recovery-period|Contingency Event Recovery Period}} and then restoring contingency reserve within the applicable {{reserve-restoration-period|restoration period}}. Entity and Reserve Sharing Group procedures determine the actual resources and coordination."
      },
      {
        "t": "interactive",
        "id": "interchangeLifecycle"
      },
      {
        "t": "scenario",
        "title": "Unit trip during an interchange ramp",
        "role": "Balancing Authority Operator",
        "setup": "A 1,000 MW unit trips while a 300 MW import is ramping into the BA. Frequency is low, tie-line metering is valid, and ACE becomes strongly negative.",
        "steps": [
          {
            "stem": "Which sequence best describes the response?",
            "options": [
              "Cancel all schedules first, then wait for frequency to recover",
              "Recognize primary frequency response, deploy contingency reserves and AGC or manual control, track ACE recovery, coordinate schedule effects, then rebuild reserves",
              "Use reactive devices to restore ACE",
              "Change the frequency bias to hide the ACE magnitude"
            ],
            "answer": 1,
            "explain": "Primary response arrests frequency. Secondary and contingency actions restore balance and ACE. Schedule and accounting effects are coordinated without redefining the measurement to make the event disappear.",
            "optFeedback": {
              "0": "Schedules may need coordination, but balance and recovery actions cannot wait.",
              "2": "Reactive devices support voltage, not the real-power imbalance measured by ACE.",
              "3": "Bias is a parameter, not an emergency correction for unfavorable ACE."
            }
          }
        ],
        "debrief": "A balancing event spans physics, control systems, schedules, reserves, communications, and accounting. The operator must keep those layers separate while managing them together."
      }
    ]
  }
]);
  window.NERC.glossary = (window.NERC.glossary || []).concat([
  {
    "id": "human-performance",
    "term": "Human Performance",
    "definition": "The use of tools, behaviors, and organizational defenses to reduce the likelihood and consequences of human error during work.",
    "seeAlso": [
      "self-check",
      "peer-check",
      "placekeeping"
    ],
    "moduleRef": "f-human-performance"
  },
  {
    "id": "self-check",
    "term": "Self-Check",
    "definition": "A deliberate pause before action to identify the correct component or control, state the intended action and expected result, perform it, and verify the actual result.",
    "seeAlso": [
      "human-performance"
    ],
    "moduleRef": "f-human-performance"
  },
  {
    "id": "peer-check",
    "term": "Peer Check",
    "definition": "An independent confirmation by another qualified person before a selected high-risk action is performed.",
    "seeAlso": [
      "human-performance"
    ],
    "moduleRef": "f-human-performance"
  },
  {
    "id": "placekeeping",
    "term": "Placekeeping",
    "definition": "A method for visibly tracking progress through a procedure so steps are not skipped, repeated, or performed out of order.",
    "seeAlso": [
      "human-performance"
    ],
    "moduleRef": "f-human-performance"
  },
  {
    "id": "stop-work",
    "term": "Stop-Work Behavior",
    "definition": "Pausing an activity when conditions, indications, procedure steps, or expected results do not match, until the discrepancy is resolved.",
    "seeAlso": [
      "human-performance"
    ],
    "moduleRef": "f-human-performance"
  },
  {
    "id": "ied",
    "term": "Intelligent Electronic Device",
    "definition": "A microprocessor-based field device that measures, protects, controls, records, or communicates information about power-system equipment.",
    "acronym": "IED",
    "seeAlso": [
      "rtu",
      "scada"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "rtu",
    "term": "Remote Terminal Unit",
    "definition": "A field device or gateway that collects status and analog data and exchanges control commands with the control center.",
    "acronym": "RTU",
    "seeAlso": [
      "ied",
      "scada"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "iccp",
    "term": "Inter-Control Center Communications Protocol",
    "definition": "A protocol and data-exchange arrangement used to share selected real-time information between control centers.",
    "acronym": "ICCP",
    "seeAlso": [
      "scada",
      "ems"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "pmu",
    "term": "Phasor Measurement Unit",
    "definition": "A device that measures synchronized voltage and current phasors, frequency, and rate of change using a common time reference.",
    "acronym": "PMU",
    "seeAlso": [
      "state-estimator"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "topology-processor",
    "term": "Topology Processor",
    "definition": "The EMS function that uses breaker and switch statuses to build the electrical network model used by state estimation and analysis.",
    "seeAlso": [
      "state-estimator",
      "scada"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "observability",
    "term": "Observability",
    "definition": "The condition in which enough usable measurements and model information are available to estimate the system state.",
    "seeAlso": [
      "state-estimator",
      "convergence"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "convergence",
    "term": "Convergence",
    "definition": "Successful completion of an iterative analysis in which the solution settles to an acceptable consistent result. Failure to converge can indicate model, topology, or measurement problems.",
    "seeAlso": [
      "state-estimator",
      "bad-data"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "bad-data",
    "term": "Bad Data",
    "definition": "A measurement or status that is incorrect, inconsistent, or mapped improperly and can distort monitoring or analysis.",
    "seeAlso": [
      "data-quality-flag",
      "stale-telemetry"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "stale-telemetry",
    "term": "Stale Telemetry",
    "definition": "A value that has not refreshed within the expected time and may no longer represent current conditions.",
    "seeAlso": [
      "data-quality-flag",
      "bad-data"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "sequence-of-events",
    "term": "Sequence of Events",
    "definition": "Time-ordered, high-resolution records of status changes, relay operations, and alarms used to reconstruct a disturbance.",
    "acronym": "SOE",
    "seeAlso": [
      "relay-target",
      "breaker-failure"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "alarm-flood",
    "term": "Alarm Flood",
    "definition": "A burst of alarms arriving faster than an operator can easily process, often following a disturbance or communications problem.",
    "seeAlso": [
      "scada",
      "human-performance"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "data-quality-flag",
    "term": "Data Quality Flag",
    "definition": "A tag that indicates whether a data point is good, questionable, stale, substituted, failed, or otherwise limited.",
    "seeAlso": [
      "bad-data",
      "stale-telemetry"
    ],
    "moduleRef": "m1-ems-data-quality"
  },
  {
    "id": "facility-rating",
    "term": "Facility Rating",
    "definition": "The operating limit of a facility or element based on the most limiting applicable equipment and conditions, as established by the responsible owner.",
    "seeAlso": [
      "normal-rating",
      "emergency-rating",
      "sol"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "normal-rating",
    "term": "Normal Rating",
    "definition": "A rating intended for operation under specified normal conditions, commonly for continuous or routine duration as defined by the owner.",
    "seeAlso": [
      "emergency-rating",
      "facility-rating"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "emergency-rating",
    "term": "Emergency Rating",
    "definition": "A rating that permits operation under specified emergency conditions for a defined duration or condition. The exact value and time come from approved rating information.",
    "seeAlso": [
      "normal-rating",
      "facility-rating"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "system-voltage-limit",
    "term": "System Voltage Limit",
    "definition": "A voltage-related system limit established for specified conditions and configurations.",
    "seeAlso": [
      "sol",
      "voltage"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "limiting-contingency",
    "term": "Limiting Contingency",
    "definition": "The contingency that produces the binding or most restrictive monitored result for a particular condition.",
    "seeAlso": [
      "contingency",
      "sol",
      "irol"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "irol-tv",
    "term": "IROL Tv",
    "definition": "The maximum time established for returning a system from an IROL exceedance to within the IROL. The value is specific to the IROL and approved methodology or plan.",
    "acronym": "IROL Tv",
    "seeAlso": [
      "irol"
    ],
    "moduleRef": "m3-ratings-to-action"
  },
  {
    "id": "ct",
    "term": "Current Transformer",
    "definition": "An instrument transformer that provides a scaled current signal for meters, relays, and control equipment.",
    "acronym": "CT",
    "seeAlso": [
      "pt-ccvt",
      "protection-zone"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "pt-ccvt",
    "term": "Potential Transformer / Capacitive Coupled Voltage Transformer",
    "definition": "Instrument transformers that provide scaled voltage signals for metering, protection, synchronization, and control.",
    "acronym": "PT/CCVT",
    "seeAlso": [
      "ct",
      "synch-check"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "protection-zone",
    "term": "Protection Zone",
    "definition": "The defined equipment area covered by a protection scheme, commonly bounded by current-transformer locations and interrupting devices.",
    "seeAlso": [
      "primary-protection",
      "backup-protection"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "primary-protection",
    "term": "Primary Protection",
    "definition": "The protection intended to detect and clear a fault first for its assigned zone.",
    "seeAlso": [
      "backup-protection",
      "protection-zone"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "backup-protection",
    "term": "Backup Protection",
    "definition": "Protection designed to clear a fault if the primary protection or interrupting device does not complete the intended clearing.",
    "seeAlso": [
      "primary-protection",
      "breaker-failure"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "distance-relay",
    "term": "Distance Relay",
    "definition": "A relay that uses measured voltage and current to estimate apparent impedance and identify faults within configured reach zones.",
    "seeAlso": [
      "directional-relay",
      "protection-zone"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "differential-relay",
    "term": "Differential Relay",
    "definition": "A relay that compares current entering and leaving a protected zone; a significant difference indicates an internal fault.",
    "seeAlso": [
      "protection-zone"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "directional-relay",
    "term": "Directional Relay",
    "definition": "A relay element that determines the direction of fault current or power relative to the relay location.",
    "seeAlso": [
      "distance-relay"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "pilot-protection",
    "term": "Pilot Protection",
    "definition": "A communications-assisted protection scheme in which terminals exchange information to achieve fast and selective fault clearing.",
    "seeAlso": [
      "transfer-trip"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "transfer-trip",
    "term": "Transfer Trip",
    "definition": "A signal sent from one terminal or device to trip a remote breaker or equipment as part of a protection or control scheme.",
    "seeAlso": [
      "pilot-protection"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "breaker-failure",
    "term": "Breaker Failure Protection",
    "definition": "Protection that detects when a commanded breaker has not interrupted current and trips surrounding breakers to clear the fault.",
    "acronym": "50BF",
    "seeAlso": [
      "backup-protection",
      "sequence-of-events"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "lockout-relay",
    "term": "Lockout Relay",
    "definition": "A latching auxiliary relay that trips and blocks selected equipment from reclosing until it is deliberately reset under approved procedures.",
    "acronym": "86",
    "seeAlso": [
      "reclosing"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "reclosing",
    "term": "Automatic Reclosing",
    "definition": "Automatic closing of a breaker after a trip when the scheme and conditions permit, commonly used to restore a line after a temporary fault.",
    "seeAlso": [
      "synch-check",
      "lockout-relay"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "synch-check",
    "term": "Synchronism Check",
    "definition": "A protective or control function that permits closing only when voltage, frequency, and phase-angle conditions are acceptable.",
    "acronym": "25",
    "seeAlso": [
      "slip-frequency",
      "pt-ccvt"
    ],
    "moduleRef": "m6-restoration-constraints"
  },
  {
    "id": "relay-target",
    "term": "Relay Target",
    "definition": "An indication showing which relay element or function operated, used with SOE and other evidence to understand an event.",
    "seeAlso": [
      "sequence-of-events"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "protection-misoperation",
    "term": "Protection System Misoperation",
    "definition": "A failure of a protection system to operate as intended, including failure to trip, slow trip, unnecessary trip, or unintended operation.",
    "seeAlso": [
      "primary-protection",
      "backup-protection"
    ],
    "moduleRef": "m4-event-reconstruction"
  },
  {
    "id": "avr",
    "term": "Automatic Voltage Regulator",
    "definition": "A generator control that adjusts excitation to regulate terminal voltage or reactive output within equipment and limiter constraints.",
    "acronym": "AVR",
    "seeAlso": [
      "oel",
      "uel",
      "reactive-reserve"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "oel",
    "term": "Overexcitation Limiter",
    "definition": "A generator excitation-system limiter that restricts field current to protect the rotor from overheating or damage.",
    "acronym": "OEL",
    "seeAlso": [
      "avr",
      "generator-capability-curve"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "uel",
    "term": "Underexcitation Limiter",
    "definition": "A generator excitation-system limiter that prevents operation too far into the underexcited region where stability or heating limits may be exceeded.",
    "acronym": "UEL",
    "seeAlso": [
      "avr",
      "generator-capability-curve"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "reactive-reserve",
    "term": "Reactive Reserve",
    "definition": "The remaining reactive-power capability available from generators or other devices to respond to changing voltage conditions and contingencies.",
    "seeAlso": [
      "generator-capability-curve",
      "reactive-power"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "generator-capability-curve",
    "term": "Generator Capability Curve",
    "definition": "A chart showing the combinations of MW and MVAR a generator can produce or absorb without exceeding stator-current, field-current, stability, or other limits.",
    "seeAlso": [
      "oel",
      "uel",
      "reactive-reserve"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "ltc",
    "term": "Load Tap Changer",
    "definition": "A transformer mechanism that changes turns ratio under load to regulate voltage. Its action can change the load and reactive burden seen by the transmission system.",
    "acronym": "LTC",
    "seeAlso": [
      "voltage"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "svc",
    "term": "Static VAR Compensator",
    "definition": "A fast shunt reactive device using power electronics and reactors or capacitors to regulate voltage.",
    "acronym": "SVC",
    "seeAlso": [
      "statcom",
      "reactive-power"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "statcom",
    "term": "Static Synchronous Compensator",
    "definition": "A voltage-source-converter device that rapidly supplies or absorbs reactive current to support voltage.",
    "acronym": "STATCOM",
    "seeAlso": [
      "svc",
      "reactive-power"
    ],
    "moduleRef": "m2-control-devices"
  },
  {
    "id": "operational-planning-analysis",
    "term": "Operational Planning Analysis",
    "definition": "An evaluation of expected system conditions for a future operating period, including contingencies, risks, and possible actions.",
    "acronym": "OPA",
    "seeAlso": [
      "operating-plan"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "operating-plan",
    "term": "Operating Plan",
    "definition": "A documented plan that identifies actions, responsibilities, communications, and conditions for reliable operation under expected or emergency conditions.",
    "seeAlso": [
      "operational-planning-analysis"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "eea",
    "term": "Energy Emergency Alert",
    "definition": "A reliability communication framework used to describe and coordinate escalating energy emergency conditions.",
    "acronym": "EEA",
    "seeAlso": [
      "capacity-deficiency",
      "demand-response"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "ufls",
    "term": "Underfrequency Load Shedding",
    "definition": "Automatic load shedding designed to arrest severe frequency decline and help preserve the Interconnection.",
    "acronym": "UFLS",
    "seeAlso": [
      "frequency",
      "uvls"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "uvls",
    "term": "Undervoltage Load Shedding",
    "definition": "Automatic load shedding designed to reduce demand when severe low-voltage conditions threaten voltage stability.",
    "acronym": "UVLS",
    "seeAlso": [
      "voltage",
      "ufls"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "demand-response",
    "term": "Demand Response",
    "definition": "A planned change in customer demand in response to reliability, price, or program signals.",
    "acronym": "DR",
    "seeAlso": [
      "interruptible-load",
      "capacity-deficiency"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "interruptible-load",
    "term": "Interruptible Load",
    "definition": "Demand that can be reduced or interrupted under an agreement or tariff when specified conditions occur.",
    "seeAlso": [
      "demand-response"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "capacity-deficiency",
    "term": "Capacity Deficiency",
    "definition": "A condition in which expected available resources and firm imports are insufficient to meet forecast demand and required reserves.",
    "seeAlso": [
      "eea",
      "operating-plan"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "loss-of-ems",
    "term": "Loss of EMS Functionality",
    "definition": "Loss or degradation of one or more energy-management-system capabilities such as monitoring, alarms, state estimation, contingency analysis, or control.",
    "seeAlso": [
      "ems",
      "alternate-control-center"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "alternate-control-center",
    "term": "Alternate Control Center",
    "definition": "A backup location or capability used to continue required monitoring, control, logging, alarming, data exchange, and communications when the primary control center is unavailable.",
    "seeAlso": [
      "loss-of-ems"
    ],
    "moduleRef": "m5-operating-plan-tabletop"
  },
  {
    "id": "station-service",
    "term": "Station Service",
    "definition": "Electric supply used by substation or generating-station equipment such as controls, pumps, cooling, lighting, and battery chargers.",
    "seeAlso": [
      "auxiliary-load"
    ],
    "moduleRef": "m6-restoration-constraints"
  },
  {
    "id": "auxiliary-load",
    "term": "Generator Auxiliary Load",
    "definition": "The internal electrical demand required to start and operate a generating unit and its supporting equipment.",
    "seeAlso": [
      "station-service",
      "blackstart"
    ],
    "moduleRef": "m6-restoration-constraints"
  },
  {
    "id": "slip-frequency",
    "term": "Slip Frequency",
    "definition": "The difference in frequency between two energized systems being synchronized, which determines how quickly their phase-angle difference changes.",
    "seeAlso": [
      "synch-check"
    ],
    "moduleRef": "m6-restoration-constraints"
  },
  {
    "id": "transformer-inrush",
    "term": "Transformer Inrush Current",
    "definition": "A large temporary magnetizing current that can occur when a transformer is energized, especially depending on switching angle and residual flux.",
    "seeAlso": [
      "transformer-eq"
    ],
    "moduleRef": "m6-restoration-constraints"
  },
  {
    "id": "operating-instruction",
    "term": "Operating Instruction",
    "definition": "A communicated instruction for operating the interconnected power system that requires clear, standardized communication under applicable procedures.",
    "seeAlso": [
      "reliability-directive",
      "repeat-back"
    ],
    "moduleRef": "m7-directives-fallback"
  },
  {
    "id": "reliability-directive",
    "term": "Reliability Directive",
    "definition": "An instruction issued under applicable reliability authority to address an actual or anticipated reliability condition.",
    "seeAlso": [
      "operating-instruction",
      "rc"
    ],
    "moduleRef": "m7-directives-fallback"
  },
  {
    "id": "repeat-back",
    "term": "Repeat-Back",
    "definition": "The receiver restates an instruction to the issuer so the issuer can verify that it was heard and understood correctly.",
    "seeAlso": [
      "acknowledgment"
    ],
    "moduleRef": "m7-directives-fallback"
  },
  {
    "id": "acknowledgment",
    "term": "Acknowledgment",
    "definition": "The issuer confirms that a repeat-back is correct, or corrects it before the instructed action is performed.",
    "seeAlso": [
      "repeat-back"
    ],
    "moduleRef": "m7-directives-fallback"
  },
  {
    "id": "arranged-interchange",
    "term": "Arranged Interchange",
    "definition": "Interchange information submitted for reliability evaluation and approval before implementation.",
    "seeAlso": [
      "confirmed-interchange",
      "e-tag"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "confirmed-interchange",
    "term": "Confirmed Interchange",
    "definition": "Arranged Interchange that has completed the required approval and confirmation process and is ready for implementation.",
    "seeAlso": [
      "arranged-interchange",
      "implemented-interchange"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "implemented-interchange",
    "term": "Implemented Interchange",
    "definition": "The agreed interchange schedule as implemented by the Balancing Authorities, including the applicable ramp and profile.",
    "seeAlso": [
      "confirmed-interchange",
      "interchange"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "e-tag",
    "term": "Electronic Tag",
    "definition": "The electronic record used to communicate interchange transaction information, path, profile, approvals, and modifications.",
    "acronym": "e-Tag",
    "seeAlso": [
      "arranged-interchange",
      "confirmed-interchange"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "dynamic-schedule",
    "term": "Dynamic Schedule",
    "definition": "A telemetered time-varying interchange schedule or arrangement that changes with a resource or load rather than remaining a fixed hourly profile.",
    "seeAlso": [
      "pseudo-tie",
      "implemented-interchange"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "pseudo-tie",
    "term": "Pseudo-Tie",
    "definition": "A dynamic transfer arrangement that places a remote generating unit or load into the receiving Balancing Authority's control and accounting as if it were internal.",
    "seeAlso": [
      "dynamic-schedule"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "inadvertent-interchange",
    "term": "Inadvertent Interchange",
    "definition": "The accumulated difference between actual and scheduled interchange over time.",
    "seeAlso": [
      "implemented-interchange",
      "ace"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "time-error",
    "term": "Time Error",
    "definition": "The accumulated difference between Interconnection time based on system frequency and a reference time standard.",
    "seeAlso": [
      "frequency"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "rbce",
    "term": "Reportable Balancing Contingency Event",
    "definition": "A balancing contingency event that meets the reporting criteria used for disturbance-control performance and recovery.",
    "acronym": "RBCE",
    "seeAlso": [
      "contingency-event-recovery-period"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "contingency-event-recovery-period",
    "term": "Contingency Event Recovery Period",
    "definition": "The applicable period in which the responsible entity must demonstrate ACE recovery following a reportable balancing contingency event.",
    "acronym": "CERP",
    "seeAlso": [
      "rbce",
      "reserve-restoration-period"
    ],
    "moduleRef": "m8-interchange-recovery"
  },
  {
    "id": "reserve-restoration-period",
    "term": "Contingency Reserve Restoration Period",
    "definition": "The applicable period for restoring deployed contingency reserve after the recovery from a balancing contingency event.",
    "seeAlso": [
      "operating-reserve",
      "rbce"
    ],
    "moduleRef": "m8-interchange-recovery"
  }
]);
  /* Merge Phase 2 glossary enhancements into existing entries rather than
     exposing duplicate terms in search and lesson popovers. Newer Phase 2
     definitions and lesson links win; genuinely new terms remain appended. */
  (function(){
    var byId = {};
    window.NERC.glossary = (window.NERC.glossary || []).filter(function(entry){
      if (!byId[entry.id]) { byId[entry.id] = entry; return true; }
      Object.assign(byId[entry.id], entry);
      return false;
    });
  })();
  window.NERC.questions = (window.NERC.questions || []).concat([
  {
    "id": "q-p2-001",
    "module": "protection",
    "section": "m4-event-reconstruction",
    "domain": "transmission",
    "topic": "2a",
    "difficulty": "application",
    "stem": "A line relay targets Zone 1, the line breaker receives a trip, current remains high, and adjacent bus breakers trip 150 ms later. What is the best interpretation?",
    "options": [
      "Breaker-failure protection cleared the fault through surrounding breakers",
      "Normal reclosing restored the line",
      "The state estimator changed the topology",
      "A shunt reactor operated"
    ],
    "answer": 0,
    "explain": "The sequence indicates that the primary breaker did not interrupt current and breaker-failure backup tripped adjacent breakers.",
    "std": "PRC-027-1"
  },
  {
    "id": "q-p2-002",
    "module": "protection",
    "section": "m4-event-reconstruction",
    "domain": "transmission",
    "topic": "2a",
    "difficulty": "recall",
    "stem": "Which scheme compares current entering and leaving a defined protection zone?",
    "options": [
      "Distance protection",
      "Differential protection",
      "Directional overcurrent",
      "Underfrequency protection"
    ],
    "answer": 1,
    "explain": "Differential protection compares the currents at the boundaries of a zone and operates for an internal difference.",
    "std": "PRC-027-1"
  },
  {
    "id": "q-p2-003",
    "module": "protection",
    "section": "m4-event-reconstruction",
    "domain": "transmission",
    "topic": "2a",
    "difficulty": "analysis",
    "stem": "After a disturbance, which information set is most useful for reconstructing what operated first?",
    "options": [
      "Only the final one-line",
      "Only the operator voice log",
      "Time-synchronized SOE records, relay targets, breaker status, and current",
      "Only the last alarm received"
    ],
    "answer": 2,
    "explain": "High-resolution time order plus relay and electrical evidence supports a defensible event reconstruction.",
    "std": "PRC-004-6"
  },
  {
    "id": "q-p2-004",
    "module": "protection",
    "section": "m4-event-reconstruction",
    "domain": "transmission",
    "topic": "2a",
    "difficulty": "application",
    "stem": "A relay trips a healthy line during a stable power swing. From the operator perspective, this is best treated as:",
    "options": [
      "Normal primary protection because any swing is a fault",
      "An interchange scheduling problem",
      "A voltage schedule violation only",
      "A potential protection misoperation that must be preserved, reported, and investigated"
    ],
    "answer": 3,
    "explain": "An unnecessary trip is a potential misoperation. Preserve evidence, communicate the topology change, and follow the applicable review process.",
    "std": "PRC-004-6"
  },
  {
    "id": "q-p2-005",
    "module": "voltage-reactive",
    "section": "m2-control-devices",
    "domain": "transmission",
    "topic": "2b",
    "difficulty": "application",
    "stem": "A weak transmission bus is at 0.92 pu and a nearby generator is close to its maximum MVAR output. Which action is generally most appropriate?",
    "options": [
      "Coordinate nearby reactive support and manage LTC action while preserving generator margin",
      "Switch in a shunt reactor",
      "Raise all downstream LTCs without coordination",
      "Reduce local generation and increase imports"
    ],
    "answer": 0,
    "explain": "Nearby reactive support and controlled LTC behavior address the weak voltage while preserving margin for additional events.",
    "std": "VAR-001-5"
  },
  {
    "id": "q-p2-006",
    "module": "voltage-reactive",
    "section": "m2-control-devices",
    "domain": "transmission",
    "topic": "2b",
    "difficulty": "recall",
    "stem": "What does an overexcitation limiter primarily protect against?",
    "options": [
      "Low system frequency",
      "Excessive generator field current",
      "Breaker failure",
      "Excessive scheduled interchange"
    ],
    "answer": 1,
    "explain": "The OEL limits excitation or field current to protect the generator rotor and excitation system.",
    "std": "PRC-019-2"
  },
  {
    "id": "q-p2-007",
    "module": "voltage-reactive",
    "section": "m2-control-devices",
    "domain": "transmission",
    "topic": "2b",
    "difficulty": "analysis",
    "stem": "Why can aggressive LTC action be harmful during transmission voltage weakness?",
    "options": [
      "It always trips the transformer differential relay",
      "It directly lowers frequency bias",
      "It can restore distribution voltage while increasing load and reactive burden on the weak transmission source",
      "It removes all capacitor banks"
    ],
    "answer": 2,
    "explain": "LTC action can make the local load draw more power or MVAR, deepening the burden upstream even while customer voltage initially improves.",
    "std": "VAR-001-5"
  },
  {
    "id": "q-p2-008",
    "module": "operating-limits",
    "section": "m3-ratings-to-action",
    "domain": "transmission",
    "topic": "2e",
    "difficulty": "recall",
    "stem": "Which statement best distinguishes a Facility Rating from an SOL?",
    "options": [
      "They are always identical",
      "An SOL applies only to generation",
      "A Facility Rating is calculated by the state estimator every minute",
      "A Facility Rating is equipment capability information; an SOL is a system operating limit for specified conditions"
    ],
    "answer": 3,
    "explain": "Ratings describe equipment capability; SOLs are system limits established using applicable methodologies, configurations, and conditions.",
    "std": "FAC-011-4"
  },
  {
    "id": "q-p2-009",
    "module": "operating-limits",
    "section": "m3-ratings-to-action",
    "domain": "contingency",
    "topic": "5e",
    "difficulty": "analysis",
    "stem": "A post-contingency result exceeds an IROL, and the highest-relief action cannot be completed until after the established IROL Tv. What is the best response?",
    "options": [
      "Implement actions that can return the system within the IROL Tv and verify the updated assessment",
      "Use only that action because it gives the most relief eventually",
      "Wait for the contingency to occur before acting",
      "Rename the IROL as an SOL"
    ],
    "answer": 0,
    "explain": "The action plan must be executable within the established time and verified through updated analysis.",
    "std": "IRO-009-2"
  },
  {
    "id": "q-p2-010",
    "module": "transmission-ops",
    "section": "m1-ems-data-quality",
    "domain": "transmission",
    "topic": "2f",
    "difficulty": "recall",
    "stem": "What device commonly collects field status and analog data for communication to SCADA?",
    "options": [
      "LTC",
      "RTU",
      "OEL",
      "UFLS relay"
    ],
    "answer": 1,
    "explain": "An RTU or similar gateway collects field data and exchanges information and controls with the control center.",
    "std": "TOP-010-1(i)"
  },
  {
    "id": "q-p2-011",
    "module": "transmission-ops",
    "section": "m1-ems-data-quality",
    "domain": "contingency",
    "topic": "5b",
    "difficulty": "analysis",
    "stem": "SCADA shows a breaker open, but MW and current remain nonzero and the state estimator stops converging. What should the operator conclude first?",
    "options": [
      "The line is definitely open",
      "The analog values should be deleted",
      "The topology and data are inconsistent and require verification before dependent actions",
      "The contingency analysis is more accurate than physical status"
    ],
    "answer": 2,
    "explain": "Conflicting status, analog data, and failed analysis indicate uncertainty. Stop dependent switching and verify the actual state and model.",
    "std": "TOP-010-1(i)"
  },
  {
    "id": "q-p2-012",
    "module": "transmission-ops",
    "section": "m1-ems-data-quality",
    "domain": "contingency",
    "topic": "5b",
    "difficulty": "application",
    "stem": "Which is the best reasonableness check for a questionable line-flow value?",
    "options": [
      "Assume any value inside the line rating is good",
      "Use only the alarm color",
      "Change the value manually until the state estimator converges",
      "Compare its timestamp, adjacent flows, redundant indications, and local confirmation"
    ],
    "answer": 3,
    "explain": "Data validity comes from consistency, freshness, redundancy, and verification, not from whether a number looks convenient.",
    "std": "IRO-008-3"
  },
  {
    "id": "q-p2-013",
    "module": "emergency-ops",
    "section": "m5-operating-plan-tabletop",
    "domain": "emergency-prep",
    "topic": "3a",
    "difficulty": "application",
    "stem": "A next-day analysis identifies a likely peak-hour deficiency. What is the best use of the time before the peak?",
    "options": [
      "Validate inputs, update the Operating Plan, secure resources and demand-side actions, and coordinate communications",
      "Wait for an actual emergency declaration",
      "Reduce all exports regardless of reliability impact",
      "Disable maintenance alarms"
    ],
    "answer": 0,
    "explain": "Planning time should be used to validate assumptions, arrange mitigation, communicate, and prepare escalation triggers.",
    "std": "EOP-011-4"
  },
  {
    "id": "q-p2-014",
    "module": "emergency-ops",
    "section": "m5-operating-plan-tabletop",
    "domain": "emergency-prep",
    "topic": "3b",
    "difficulty": "analysis",
    "stem": "During extreme cold, which assessment is most important when a large amount of generation is listed as available?",
    "options": [
      "Nameplate MW only",
      "Dependable capability considering fuel, temperature limitations, startup risk, and transmission deliverability",
      "The color of the weather map",
      "Last summer's peak output"
    ],
    "answer": 1,
    "explain": "Emergency planning needs dependable, deliverable capability under the forecast conditions, not just nameplate values.",
    "std": "EOP-011-4"
  },
  {
    "id": "q-p2-015",
    "module": "emergency-ops",
    "section": "m5-operating-plan-tabletop",
    "domain": "emergency-response",
    "topic": "4c",
    "difficulty": "application",
    "stem": "A capacity emergency is worsening. Which action is generally a deliberate last resort after available lower-impact measures?",
    "options": [
      "Validating the load forecast",
      "Calling available demand response",
      "Controlled firm load shedding",
      "Coordinating firm imports"
    ],
    "answer": 2,
    "explain": "Controlled firm load shed is a severe but deliberate reliability action used when available resources and lower-impact measures cannot meet demand.",
    "std": "EOP-011-4"
  },
  {
    "id": "q-p2-016",
    "module": "emergency-ops",
    "section": "m5-operating-plan-tabletop",
    "domain": "emergency-response",
    "topic": "4d",
    "difficulty": "recall",
    "stem": "The purpose of an alternate control-center plan is to:",
    "options": [
      "Eliminate the need for certified operators",
      "Replace all operating procedures with verbal direction",
      "Avoid notifying neighboring entities",
      "Continue required monitoring, control, logging, alarms, data exchange, and communications when primary functionality is lost"
    ],
    "answer": 3,
    "explain": "Backup functionality supports continued reliable operations and the entity's required functional obligations.",
    "std": "EOP-008-2"
  },
  {
    "id": "q-p2-017",
    "module": "emergency-ops",
    "section": "m5-operating-plan-tabletop",
    "domain": "emergency-response",
    "topic": "4e",
    "difficulty": "analysis",
    "stem": "The state estimator and contingency analysis are unavailable during a high-transfer condition. What is the best operating principle?",
    "options": [
      "Use fallback tools and manual verification, communicate the degradation, and apply conservative margins until capability is restored",
      "Maintain the same transfer because the last run passed",
      "Increase transfers to test whether alarms appear",
      "Ignore post-contingency risk"
    ],
    "answer": 0,
    "explain": "Loss of analysis increases uncertainty and generally calls for stronger coordination and more conservative operation.",
    "std": "TOP-010-1(i)"
  },
  {
    "id": "q-p2-018",
    "module": "restoration",
    "section": "m6-restoration-constraints",
    "domain": "emergency-response",
    "topic": "4a",
    "difficulty": "application",
    "stem": "A long unloaded line causes high voltage during restoration. Which response is best?",
    "options": [
      "Energize more unloaded line sections immediately",
      "Follow the plan's reactive-control and alternate-path provisions, stabilize voltage, then continue",
      "Pick up the largest load without checking frequency",
      "Synchronize islands with a large phase-angle difference"
    ],
    "answer": 1,
    "explain": "Restoration proceeds through stable, verified steps using planned reactive controls and alternate paths.",
    "std": "EOP-005-3"
  },
  {
    "id": "q-p2-019",
    "module": "operating-limits",
    "section": "m3-ratings-to-action",
    "domain": "contingency",
    "topic": "5a",
    "difficulty": "analysis",
    "stem": "An actual-state table is within limits, but loss of Line X produces 112% loading. What does that result mean?",
    "options": [
      "The system is secure because the line has not tripped",
      "The overload can be ignored until 120%",
      "The monitored post-contingency state requires corrective evaluation or action before the contingency occurs",
      "The state estimator must be wrong"
    ],
    "answer": 2,
    "explain": "Contingency analysis is preventive. A credible loss that produces an unacceptable result must be addressed according to the applicable plan and limit.",
    "std": "IRO-008-3"
  },
  {
    "id": "q-p2-020",
    "module": "transmission-ops",
    "section": "m1-ems-data-quality",
    "domain": "contingency",
    "topic": "5c",
    "difficulty": "application",
    "stem": "After correcting a wrong breaker status in the network model, what should the operator do before resuming a dependent switching order?",
    "options": [
      "Assume the correction fixed every tool",
      "Clear all alarms",
      "Replace the breaker",
      "Rerun or review the state estimation and contingency results, confirm the topology, and communicate as required"
    ],
    "answer": 3,
    "explain": "The model correction must be validated through updated analysis and confirmation of the actual topology.",
    "std": "TOP-010-1(i)"
  },
  {
    "id": "q-p2-021",
    "module": "operating-limits",
    "section": "m3-ratings-to-action",
    "domain": "contingency",
    "topic": "5d",
    "difficulty": "recall",
    "stem": "Which can form the basis of an SOL?",
    "options": [
      "Thermal, voltage, or stability performance as established by the applicable methodology",
      "Only thermal loading",
      "Only voltage",
      "Only transient stability"
    ],
    "answer": 0,
    "explain": "SOLs can be based on thermal, voltage, or stability limits for specified conditions.",
    "std": "FAC-011-4"
  },
  {
    "id": "q-p2-022",
    "module": "operating-limits",
    "section": "m3-ratings-to-action",
    "domain": "contingency",
    "topic": "5e",
    "difficulty": "recall",
    "stem": "What makes an IROL different from other SOLs?",
    "options": [
      "It is always a generator nameplate rating",
      "Its exceedance could lead to instability, uncontrolled separation, or cascading",
      "It applies only to distribution voltage",
      "It has no corrective-action time"
    ],
    "answer": 1,
    "explain": "IROLs are the subset of SOLs associated with severe wide-area reliability consequences.",
    "std": "IRO-009-2"
  },
  {
    "id": "q-p2-023",
    "module": "comms-coord",
    "section": "m7-directives-fallback",
    "domain": "comms-data",
    "topic": "6b",
    "difficulty": "application",
    "stem": "An instruction contains a station name that could be confused with another station. What should the receiver do?",
    "options": [
      "Choose the most likely station",
      "Ask a coworker and act without issuer confirmation",
      "Repeat back the full instruction and obtain confirmation or correction before acting",
      "Perform both possible actions"
    ],
    "answer": 2,
    "explain": "The communication loop must remove ambiguity with a complete repeat-back and issuer confirmation.",
    "std": "COM-002-4"
  },
  {
    "id": "q-p2-024",
    "module": "comms-coord",
    "section": "m7-directives-fallback",
    "domain": "comms-data",
    "topic": "6c",
    "difficulty": "analysis",
    "stem": "A voltage point is marked good, but it has not changed for 20 minutes while neighboring values move. What is the best conclusion?",
    "options": [
      "The quality flag proves it is current",
      "The bus voltage is perfectly regulated",
      "The state estimator should be disabled",
      "It may be stale or frozen and should be verified using timestamps and independent indications"
    ],
    "answer": 3,
    "explain": "A quality label is one clue. Trend continuity, timestamp, and independent evidence are needed to verify freshness.",
    "std": "TOP-010-1(i)"
  },
  {
    "id": "q-p2-025",
    "module": "comms-coord",
    "section": "m7-directives-fallback",
    "domain": "comms-data",
    "topic": "6c",
    "difficulty": "application",
    "stem": "The operator cannot carry out a directive because the breaker control is unavailable. What is the best response?",
    "options": [
      "State the inability and reason, provide relevant system information, and request or coordinate an alternative",
      "Say nothing and wait",
      "Substitute a different breaker",
      "Report completion anyway"
    ],
    "answer": 0,
    "explain": "Operators must close the loop when unable to comply rather than silently substituting or concealing the condition.",
    "std": "COM-002-4"
  },
  {
    "id": "q-p2-026",
    "module": "transmission-ops",
    "section": "m1-ems-data-quality",
    "domain": "comms-data",
    "topic": "6d",
    "difficulty": "recall",
    "stem": "ICCP is primarily used for:",
    "options": [
      "Generator excitation limiting",
      "Sharing selected data between control centers",
      "Automatic reclosing",
      "Transformer tap changing"
    ],
    "answer": 1,
    "explain": "ICCP supports inter-control-center data exchange.",
    "std": "EOP-008-2"
  },
  {
    "id": "q-p2-027",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1a",
    "difficulty": "recall",
    "stem": "Which stage has completed the required confirmation process and is ready for implementation?",
    "options": [
      "Arranged Interchange",
      "Inadvertent Interchange",
      "Confirmed Interchange",
      "Time Error"
    ],
    "answer": 2,
    "explain": "Confirmed Interchange has completed the approval and confirmation process.",
    "std": "INT-009-3"
  },
  {
    "id": "q-p2-028",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1a",
    "difficulty": "application",
    "stem": "A scheduled interchange ramp is increasing imports. In the ACE equation, what happens to scheduled interchange during the ramp?",
    "options": [
      "It remains fixed until the top of the hour",
      "It is replaced by frequency bias",
      "It becomes actual interchange",
      "It changes according to the agreed ramp profile"
    ],
    "answer": 3,
    "explain": "The implemented schedule follows the agreed ramp, so scheduled interchange changes through the ramp interval.",
    "std": "INT-009-3"
  },
  {
    "id": "q-p2-029",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1a",
    "difficulty": "analysis",
    "stem": "An overloaded interface requires a transaction curtailment. What is the best operator focus?",
    "options": [
      "Coordinate the curtailment and schedule profile, verify the reliability relief, and monitor ACE effects",
      "Change actual tie metering to match the desired schedule",
      "Ignore the e-Tag because it is commercial only",
      "Use a shunt capacitor to change the transaction"
    ],
    "answer": 0,
    "explain": "Curtailment must be coordinated and implemented so the schedule and physical relief align, while ACE and system conditions are monitored.",
    "std": "INT-006-5"
  },
  {
    "id": "q-p2-030",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1b",
    "difficulty": "application",
    "stem": "After contingency reserve is deployed for a reportable balancing event, what remains after ACE recovery?",
    "options": [
      "No further action",
      "Restore the deployed contingency reserve within the applicable restoration period",
      "Convert the reserve to reactive power",
      "Reset all tie-line meters"
    ],
    "answer": 1,
    "explain": "Recovery of ACE and restoration of contingency reserve are related but distinct parts of disturbance response.",
    "std": "BAL-002-3"
  },
  {
    "id": "q-p2-031",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1c",
    "difficulty": "analysis",
    "stem": "A large unit trips while AGC is regulating. Which sequence best separates primary and secondary response?",
    "options": [
      "AGC acts first to arrest frequency; governors act later",
      "Reactive devices restore frequency; AGC restores voltage",
      "Governors and frequency-responsive resources act immediately; AGC and dispatch then restore ACE and balance",
      "Interchange accounting arrests frequency"
    ],
    "answer": 2,
    "explain": "Primary frequency response acts automatically and quickly; secondary control follows to restore ACE and scheduled balance.",
    "std": "BAL-002-3"
  },
  {
    "id": "q-p2-032",
    "module": "balancing",
    "section": "m8-interchange-recovery",
    "domain": "balancing",
    "topic": "1d",
    "difficulty": "application",
    "stem": "Tie-line metering is valid and actual exports exceed scheduled exports by 150 MW, with frequency at schedule. What is the tie-deviation contribution to ACE?",
    "options": [
      "A negative contribution because the BA is exporting more than scheduled",
      "Zero because frequency is on schedule",
      "A reactive-power contribution",
      "A positive contribution because the BA is exporting more than scheduled"
    ],
    "answer": 3,
    "explain": "Using the common sign convention, actual export greater than scheduled export creates a positive tie-deviation term.",
    "std": "BAL-001-2"
  }
]);
})();
