(function(){
  window.NERC = window.NERC || {}; NERC.interactives = NERC.interactives || {};
  NERC.interactives.emergencyTabletop = function(root){
    var rounds=[
      {time:'Day ahead · 14:00',inject:'Peak forecast rises 700 MW. Two gas units report fuel uncertainty.',choices:[['Count both units at nameplate and wait',-20,-10,'Planning assumptions remain optimistic.'],['Validate dependable capability, update the plan, secure demand response and imports',15,15,'You use the planning horizon to build margin.'],['Shed firm load now',-10,0,'The response is premature and unnecessarily severe.']],best:1},
      {time:'Real time · 17:25',inject:'One unit trips. Operating reserve falls and the import interface reaches 97% of its limit.',choices:[['Deploy available reserve, coordinate assistance, and prepare escalation',15,10,'You address balance and deliverability together.'],['Increase imports without reviewing the interface',-15,-15,'The action worsens the constrained path.'],['Wait for UFLS',-25,-20,'UFLS is a protection backstop, not the operating plan.']],best:0},
      {time:'Real time · 17:33',inject:'State estimation and contingency analysis fail. Several tie points become stale.',choices:[['Use fallback monitoring, reduce transfer risk, and increase communications',20,20,'You shrink risk while visibility is degraded.'],['Keep the last transfer because the last run passed',-20,-20,'The last result may no longer represent the system.'],['Clear alarms to reduce workload',-15,-10,'Hiding indications does not restore situational awareness.']],best:0},
      {time:'Real time · 17:41',inject:'Available resources still trail firm demand. Frequency is declining and all lower-impact actions are exhausted.',choices:[['Implement the controlled load-shed step in the operating plan and coordinate restoration conditions',20,20,'A severe action is taken deliberately before uncontrolled collapse.'],['Continue appeals and take no physical action',-25,-25,'The condition now requires direct balance restoration.'],['Change frequency bias',-20,-20,'Changing a parameter does not create energy.']],best:0}
    ], idx=0, margin=45, awareness=70;
    root.innerHTML='<div class="c-int p2-lab"><div class="c-int__title">Emergency operations tabletop</div><div class="p2-kpis"></div><div class="p2-panel"></div></div>';
    var k=root.querySelector('.p2-kpis'), p=root.querySelector('.p2-panel');
    function render(){k.innerHTML='<div class="p2-kpi"><span>Supply margin</span><strong class="'+(margin<30?'is-bad':margin<55?'is-alert':'is-good')+'">'+margin+'%</strong></div><div class="p2-kpi"><span>Situational awareness</span><strong class="'+(awareness<35?'is-bad':awareness<60?'is-alert':'is-good')+'">'+awareness+'%</strong></div><div class="p2-kpi"><span>Inject</span><strong>'+(idx+1)+' / '+rounds.length+'</strong></div>';var r=rounds[idx];p.innerHTML='<div class="p2-time">'+r.time+'</div><h4>'+r.inject+'</h4><div class="p2-options"></div><div class="p2-feedback" aria-live="polite"></div>';var o=p.querySelector('.p2-options');r.choices.forEach(function(c,i){var b=document.createElement('button');b.className='c-btn p2-choice';b.type='button';b.textContent=c[0];b.onclick=function(){choose(i);};o.appendChild(b);});}
    function choose(i){var r=rounds[idx], c=r.choices[i];margin=Math.max(0,Math.min(100,margin+c[1]));awareness=Math.max(0,Math.min(100,awareness+c[2]));p.querySelectorAll('button').forEach(function(b){b.disabled=true;});var f=p.querySelector('.p2-feedback');f.innerHTML='<strong>'+(i===r.best?'Best available action.':'This increases risk.')+'</strong><p>'+c[3]+'</p>';var n=document.createElement('button');n.className='c-btn c-btn--primary';n.type='button';n.textContent=idx<rounds.length-1?'Next inject →':'Restart tabletop';n.onclick=function(){if(idx<rounds.length-1)idx++;else{idx=0;margin=45;awareness=70;}render();};f.appendChild(n);k.innerHTML='<div class="p2-kpi"><span>Supply margin</span><strong>'+margin+'%</strong></div><div class="p2-kpi"><span>Situational awareness</span><strong>'+awareness+'%</strong></div><div class="p2-kpi"><span>Inject</span><strong>'+(idx+1)+' / '+rounds.length+'</strong></div>';}
    render();
  };
})();
