window.NERC = window.NERC || {}; NERC.interactives = NERC.interactives || {};
NERC.interactives.equipmentPrimer = function (root) {
  var items={
    breaker:{name:"Circuit breaker",label:"Interrupts load and fault current",watch:"Position, current, control power, protection targets, and interrupting capability.",shape:'<rect x="124" y="55" width="36" height="36" rx="4"/><line x1="40" y1="73" x2="124" y2="73"/><line x1="160" y1="73" x2="244" y2="73"/><line x1="130" y1="84" x2="154" y2="62"/>'},
    transformer:{name:"Power transformer",label:"Changes voltage and transfers power between buses",watch:"MVA, winding temperature, cooling, taps, oil or pressure alarms, and differential protection.",shape:'<line x1="40" y1="73" x2="104" y2="73"/><circle cx="126" cy="73" r="24"/><circle cx="160" cy="73" r="24"/><line x1="184" y1="73" x2="244" y2="73"/>'},
    ctpt:{name:"CT and PT/CCVT",label:"Provide scaled current and voltage to meters and relays",watch:"Data quality, fuse or circuit alarms, secondary problems, and whether related values remain reasonable.",shape:'<line x1="40" y1="73" x2="244" y2="73"/><circle cx="115" cy="73" r="18"/><circle cx="169" cy="73" r="18"/><text x="115" y="78" text-anchor="middle">CT</text><text x="169" y="78" text-anchor="middle">PT</text>'},
    disconnect:{name:"Disconnect switch",label:"Provides a visible isolation point; not normally a fault-interrupting device",watch:"Use the approved sequence. Verify current interruption by the breaker before operating the disconnect.",shape:'<line x1="40" y1="73" x2="120" y2="73"/><circle cx="120" cy="73" r="4"/><circle cx="174" cy="73" r="4"/><line x1="120" y1="73" x2="168" y2="42"/><line x1="174" y1="73" x2="244" y2="73"/>'}
  };
  root.innerHTML='<div class="c-int"><div class="c-int__title">Transmission equipment primer</div><p class="p2-intro">Select a device to connect the one-line symbol with what an operator monitors.</p><div class="p3-equip-tabs" role="tablist" aria-label="Equipment type"></div><div class="p3-equip-body"><svg viewBox="0 0 284 145" role="img" aria-label="One-line symbol for the selected transmission device"><g id="ep-shape" fill="none" stroke="var(--phosphor)" stroke-width="3"></g></svg><div><h3 id="ep-name" class="c-h2"></h3><p id="ep-label"></p><div class="c-note c-note--op"><div class="c-note__title">Operator watch items</div><span id="ep-watch"></span></div></div></div></div>';
  var tabs=root.querySelector('.p3-equip-tabs'),shape=root.querySelector('#ep-shape');
  function show(key){var d=items[key];shape.innerHTML=d.shape;root.querySelector('#ep-name').textContent=d.name;root.querySelector('#ep-label').textContent=d.label;root.querySelector('#ep-watch').textContent=d.watch;tabs.querySelectorAll('button').forEach(function(b){var on=b.dataset.key===key;b.setAttribute('aria-selected',on?'true':'false');b.classList.toggle('is-on',on);});}
  Object.keys(items).forEach(function(k){var b=document.createElement('button');b.type='button';b.className='c-chip';b.dataset.key=k;b.setAttribute('role','tab');b.textContent=items[k].name;b.addEventListener('click',function(){show(k);});tabs.appendChild(b);});show('breaker');
};
